apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sre-app

resources:
  - namespace.yaml
  - configmaps.yaml
  - postgres.yaml
  - auth.yaml
  - user.yaml
  - product.yaml
  - payment.yaml
  - notification.yaml
  - order.yaml
  - frontend.yaml
  - monitoring.yaml
  - hpa.yaml

